🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/getart b/bin/getart
--- a/bin/getart
+++ b/bin/getart
@@ -1,41 +1,89 @@
 #!/usr/bin/env bash
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="getart"
+USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version     : 012520211631-git
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : getart
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : returns album art for the "artist - album" input string
-#
+##@Version       : 031520211823-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : getart --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Monday, Mar 15, 2021 18:23 EDT
+# @File          : getart
+# @Description   : returns album art for the "artist - album" input string
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-[[ -z "$ARTDIR" ]] && ARTDIR="$HOME/.cache/albumart"
-[[ -d "$ARTDIR" ]] || mkdir -p "$ARTDIR"
-
-declare mpccurrent artfile
-mpccurrent="$(echo "$@" | sed -r 's/(\[|\]|\,)//g')"
-artfile=$(find "$ARTDIR" -iname "${mpccurrent}*")
-[[ -z "$artfile" ]] && {
-  # customize useragent at http://whatsmyuseragent.com/
-  useragent='Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0'
-  link imagelink ext imagepath
-  link="www.google.com/search?q=$(urlencode "$mpccurrent")\&tbm=isch"
-  #imagelinks=$(wget -e robots=off --user-agent "$useragent" -qO - "$link" | sed 's/</\n</g' | grep '<a href.*\(png\|jpg\|jpeg\)' | sed 's/.*imgurl=\([^&]*\)\&.*/\1/')
-  imagelinks=$(timeout 10s wget -e robots=off --user-agent "$useragent" -o /dev/null -qO - "$link" | sed 's/</\n</g' | grep "ou\":\"http" | sed -nr 's/.*ou\":\"([^"]+).*/\1/p')
-  for imagelink in $imagelinks; do
-    imagelink=$(echo "$imagelink" | sed -nr 's/(.*\.(jpg|jpeg|png)).*/\1/p')
-    ext=$(echo "$imagelink" | sed -nr 's/.*(\.(jpg|jpeg|png)).*/\1/p')
-    imagepath="${ARTDIR}/${mpccurrent}${ext}"
-    timeout 10s wget --max-redirect 0 -o /dev/null -qO "$imagepath" "${imagelink}"
-    [[ -s "$imagepath" ]] && break
-    rm "$imagepath" # remove zero length file
-  done
-  artfile=$(find "$ARTDIR" -iname "${mpccurrent}*")
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# helper function
+__version() { app_version; }
+__help() {
+  app_help "Usage: getart  -  getart --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
 }
-echo "$artfile"
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# End
+# Main function
+main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash wget || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  local mpdserver="${MPDSERVER:-localhost}"
+  [[ -z "$ARTDIR" ]] && ARTDIR="$HOME/.cache/albumart"
+  [[ -d "$ARTDIR" ]] || mkdir -p "$ARTDIR"
+  declare mpccurrent artfile
+  mpccurrent="$(echo "$@" | sed -r 's/(\[|\]|\,)//g')"
+  artfile=$(find "$ARTDIR" -iname "${mpccurrent}*")
+  [[ -z "$artfile" ]] && am_i_online && {
+    useragent='Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0'
+   link imagelink ext imagepath 2>/dev/null
+    link="www.google.com/search?q=$(urlencode "$mpccurrent")\&tbm=isch"
+    imagelinks=$(timeout 10s wget -e robots=off --user-agent "$useragent" -o /dev/null -qO - "$link" | \
+      sed 's/</\n</g' | grep "ou\":\"http" | sed -nr 's/.*ou\":\"([^"]+).*/\1/p')
+    for imagelink in $imagelinks; do
+      imagelink=$(echo "$imagelink" | sed -nr 's/(.*\.(jpg|jpeg|png)).*/\1/p')
+      ext=$(echo "$imagelink" | sed -nr 's/.*(\.(jpg|jpeg|png)).*/\1/p')
+      imagepath="${ARTDIR}/${mpccurrent}${ext}"
+      timeout 10s wget --max-redirect 0 -o /dev/null -qO "$imagepath" "${imagelink}"
+      [[ -s "$imagepath" ]] && break
+      rm "$imagepath" # remove zero length file
+    done
+  artfile=$(find "$ARTDIR" -iname "${mpccurrent}*")
+  }
+  echo "$artfile"
+  return "${exitCode:-$?}"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
+
diff --git a/bin/mpcp b/bin/mpcp
--- a/bin/mpcp
+++ b/bin/mpcp
@@ -1,21 +1,76 @@
 #!/usr/bin/env bash
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="mpcp"
+USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version     : 012520211631-git
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : notifyart
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : sends notifications for the new title
-#
+##@Version       : 031520211319-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : mpcp --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Monday, Mar 15, 2021 13:19 EDT
+# @File          : mpcp
+# @Description   : Send commands to mpd using netcat
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-netcat="$(command -v nc 2>/dev/null || command -v netcat 2>/dev/null)"
-__nc() { $netcat -c "$@" && true || $netcat -w 1 "$@"; }
-
-echo "$@" | __nc "$MPDSERVER" 6600
-
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# End
+# helper function
+__version() { app_version; }
+__help() {
+  app_help "Usage: mpcp command"
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
+}
+__nc() { $netcat -c "$@" && true || $netcat -w 1 "$@" || return 1; }
+__msg_ok() { notifications "MPCP" "Sent $@ to $MPDSERVER" && return 0 || return 1; }
+__msg_fail() { notifications "MPCP" "Failed to send $@ to $MPDSERVER" && return 0 || return 1; }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+netcat="$(command -v nc 2>/dev/null || command -v netcat 2>/dev/null || return 1)"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error $netcat || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  local mpdserver="${MPDSERVER:-localhost}"
+  local mpdserverport="${MPDSERVER_PORT:-6600}"
+  if [ $# -ne 0 ]; then
+    echo "$@" | __nc $mpdserver $mpdserverport && __msg_ok "$@" || __msg_fail "$@"
+  else
+    __help
+  fi
+  return "${exitCode:-$?}"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
+
diff --git a/bin/mpd-module-update b/bin/mpd-module-update
--- a/bin/mpd-module-update
+++ b/bin/mpd-module-update
@@ -1,17 +1,72 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="mpd-module-update"
+USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version     : 012520211631-git
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : mpd-module-update
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : update the mpd statusbar module
-#
+##@Version       : 031520211356-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : mpd-module-update --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Monday, Mar 15, 2021 13:56 EDT
+# @File          : mpd-module-update
+# @Description   : Update the mpd statusbar module
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# helper function
+__version() { app_version; }
+__help() {
+  app_help "Usage: mpd-module-update  -  mpd-module-update --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # required app check
+  cmd_exists --error mpc || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  local mpdserver="${MPDSERVER:-localhost}"
+  local mpdserverport="${MPDSERVER_PORT:-6600}"
+  while :; do
+    [ -n "$STATUSBAR" ] && mpc -h $mpdserver -p $mpdserverport idle >/dev/null && pkill -RTMIN+11 "${STATUSBAR:?}" || break
+  done
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  return "${exitCode:-$?}"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
 
-while :; do
-  mpc idle >/dev/null && pkill -RTMIN+11 "${STATUSBAR:?}" || break
-done
diff --git a/bin/mpdd b/bin/mpdd
--- a/bin/mpdd
+++ b/bin/mpdd
@@ -1,36 +1,87 @@
 #!/usr/bin/env bash
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="mpdd"
+USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version     : 012520211631-git
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : mpdd
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Display mpd status in terminal
-#
+##@Version       : 031520211354-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : mpdd --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Monday, Mar 15, 2021 13:54 EDT
+# @File          : mpdd
+# @Description   : Display mpd status in terminal
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-declare _r _l _p
-while sleep 1; do
-  _r=$(awk 'BEGIN{FS=": "}
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# helper function
+__version() { app_version; }
+__help() {
+  app_help "Usage: mpdd  -  mpdd --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  local mpdserver="${MPDSERVER:-localhost}"
+  local mpdserverport="${MPDSERVER_PORT:-6600}"
+  declare _r _l _p
+  while sleep 1; do
+    _r=$(awk 'BEGIN{FS=": "}
                 /^Artist:/{r=r""$2};
                 /^Title:/{r=r" - "$2};
                 /^time:/{r=$2" "r};
                 /^state: play/{f=1}
               END{if(f==1){print r}}' <(
-    mpc status
-    mpc current
-  ))
+      mpc -h "$mpdserver" -p $mpdserverport status
+      mpc -h "$mpdserver" -p $mpdserverport current
+    ))
 
-  _l=${#_r}
-  [[ $_l -eq 0 ]] && continue
-  [[ -z "$_p" ]] && _p=$_l
-  echo -ne "\e[s\e[0;${_p}H\e[K\e[u"
-  _p=$((COLUMNS - _l))
-  echo -ne "\e[s\e[0;${_p}H\e[K\e[0;44m\e[1;33m${_r}\e[0m\e[u"
-done
-
+    _l=${#_r}
+    [[ $_l -eq 0 ]] && continue
+    [[ -z "$_p" ]] && _p=$_l
+    echo -ne "\e[s\e[0;${_p}H\e[K\e[u"
+    _p=$((COLUMNS - _l))
+    echo -ne "\e[s\e[0;${_p}H\e[K\e[0;44m\e[1;33m${_r}\e[0m\e[u"
+  done
+  return "${exitCode:-$?}"
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# End
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
+
diff --git a/bin/notifympd b/bin/notifympd
--- a/bin/notifympd
+++ b/bin/notifympd
@@ -1,29 +1,80 @@
 #!/usr/bin/env bash
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="notifyart"
+USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+#set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version     : 012520211631-git
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : notifyart
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : sends notifications for the new title
-#
+##@Version       : 031520211359-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : notifyart --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Monday, Mar 15, 2021 13:59 EDT
+# @File          : notifyart
+# @Description   : Sends notifications for the new title
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-declare artist album title oldartist oldtitle
-while true; do
-  artist=$(mpc current | awk -F": " '/^Artist:/{print $2}')
-  title=$(mpc current | awk -F": " '/^Title:/{print $2}')
-  album=$(mpc current | awk -F": " '/^Album:/{print $2}')
-  [[ "$artist" != "$oldartist" ]] || [[ "$title" != "$oldtitle" ]] && {
-    notifyart "$artist" "$title" "$album"
-    oldartist="$artist"
-    oldtitle="$title"
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# helper function
+__version() { app_version; }
+__help() {
+  app_help "Usage: notifympd  -  notifympd artist title album"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash notifyart || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  local mpdserver="${MPDSERVER:-localhost}"
+  local mpdserverport="${MPDSERVER_PORT:-6600}"
+  declare artist album title oldartist oldtitle
+  while true; do
+    artist=$(mpc -h "$mpdserver" -p $mpdserverport current | sed 's# - #: #g' | awk -F": " '{print $1}')
+    title=$(mpc -h "$mpdserver" -p $mpdserverport current | sed 's# - #: #g' | awk -F": " '{print $2}')
+    album=$(mpc -h "$mpdserver" -p $mpdserverport current | sed 's# - #: #g' | awk -F": " '{print $3}')
+    [[ "$artist" != "$oldartist" ]] || [[ "$title" != "$oldtitle" ]] && {
+      notifyart "$artist" "$title" "$album"
+      oldartist="$artist"
+      oldtitle="$title"
   }
   sleep 2
 done
-
+  return "${exitCode:-$?}"
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# End
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
+
